erDiagram
    tb_atend_prof ||--o{ rl_atend_proced : "co_atend_prof"
    tb_atend_prof_ad ||--o{ rl_atend_prof_ad_tipo_inelegvl : "co_atend_prof_ad"
    tb_atend_prof ||--o{ rl_atend_prof_conduta : "co_atend_prof"
    tb_atend_prof_odonto ||--o{ rl_atend_prof_odonto_tipo_encm : "co_atend_prof_odonto"
    tb_atend_prof_odonto ||--o{ rl_atend_prof_odonto_tipo_frnc : "co_atend_prof_odonto"
    tb_atend_prof ||--o{ rl_atend_prof_pic : "co_atend_prof"
    tb_atend ||--o{ rl_atend_tipo_servico : "co_atend"
    tb_unidade_saude ||--o{ rl_cds_prontuario_unidade_saud : "co_ator_papel"
    tb_prontuario ||--o{ rl_cds_prontuario_unidade_saud : "co_prontuario"
    tb_atend_prof ||--o{ rl_evolucao_avaliacao_ciap_cid : "co_atend_prof"
    tb_atend_prof ||--o{ rl_evolucao_plano_ciap : "co_atend_prof"
    tb_atend_prof ||--o{ rl_evolucao_subjetivo_ciap : "co_atend_prof"
    tb_cidadao_grupo_ativ_col ||--o{ rl_grupo_ativ_col_cidadao : "co_cidadao"
    tb_prof_grupo_ativ_col ||--o{ rl_grupo_ativ_col_prof : "co_prof"
    tb_prof ||--o{ rl_prof_municipio : "co_ator_papel"
    tb_unidade_saude ||--o{ rl_unidade_saude_complexidade : "co_ator_papel"
    tb_unidade_saude ||--o{ rl_unidade_saude_horus : "co_unidade_saude_horus"
    tb_unidade_saude ||--o{ rl_unidade_saude_horus : "co_unidade_saude"
    tb_unidade_saude ||--o{ rl_unidade_saude_tipo_servico : "co_ator_papel"
    tb_prontuario ||--o{ tb_ad_cidadao : "co_prontuario"
    tb_prof ||--o{ tb_ad_cidadao_historico : "co_prof"
    tb_lotacao ||--o{ tb_ad_cidadao_historico : "co_lotacao"
    tb_atend_prof_ad ||--o{ tb_ad_resposta : "co_atend_prof_ad"
    tb_lotacao ||--o{ tb_agendado : "co_lotacao_criadora"
    tb_lotacao ||--o{ tb_agendado : "co_lotacao_agendada"
    tb_prontuario ||--o{ tb_agendado : "co_prontuario"
    tb_prontuario ||--o{ tb_alergia : "co_prontuario"
    tb_atend_prof ||--o{ tb_alergia_evolucao : "co_atend_prof"
    tb_prontuario ||--o{ tb_antecedente : "co_prontuario"
    tb_atend_prof ||--o{ tb_antecedente_historico : "co_atend_prof"
    tb_atend_prof ||--o{ tb_atend : "co_atend_prof"
    tb_agendado ||--o{ tb_atend : "co_agendado"
    tb_unidade_saude ||--o{ tb_atend : "co_unidade_saude"
    tb_equipe ||--o{ tb_atend : "co_equipe"
    tb_local_atend ||--o{ tb_atend : "tp_local_atend"
    tb_status_atend ||--o{ tb_atend : "st_atend"
    tb_lotacao ||--o{ tb_atend : "co_lotacao"
    tb_prontuario ||--o{ tb_atend : "co_prontuario"
    tb_classificacao_risco ||--o{ tb_atend : "co_classificacao_risco"
    tb_tipo_atend_prof ||--o{ tb_atend_prof : "tp_atend_prof"
    tb_atend ||--o{ tb_atend_prof : "co_atend"
    tb_classificacao_risco ||--o{ tb_atend_prof : "co_classificacao_risco"
    tb_lotacao ||--o{ tb_atend_prof : "co_lotacao_atend_compartilhado"
    tb_conselho_classe ||--o{ tb_atend_prof : "co_conselho_classe"
    tb_atend_prof_tipo_encam_intrn ||--o{ tb_atend_prof : "co_atend_prof_tipo_encam_intrn"
    tb_lotacao ||--o{ tb_atend_prof : "co_lotacao"
    tb_tipo_atend ||--o{ tb_atend_prof : "tp_atend"
    tb_uf ||--o{ tb_atend_prof : "co_uf_emissora_conselho_classe"
    tb_racionalidade_saude ||--o{ tb_atend_prof : "co_racionalidade_saude"
    tb_status_atend_prof ||--o{ tb_atend_prof : "st_atend_prof"
    tb_ad_origem ||--o{ tb_atend_prof_ad : "co_ad_origem"
    tb_ad_modalidade ||--o{ tb_atend_prof_ad : "co_ad_modalidade"
    tb_cid10 ||--o{ tb_atend_prof_ad : "co_cid10_secundario_2"
    tb_cid10 ||--o{ tb_atend_prof_ad : "co_cid10_secundario_1"
    tb_cid10 ||--o{ tb_atend_prof_ad : "co_cid10_principal"
    tb_ad_destino ||--o{ tb_atend_prof_ad : "co_ad_destino"
    tb_cds_tipo_cuidador ||--o{ tb_atend_prof_ad : "tp_cds_cuidador"
    tb_atend_prof ||--o{ tb_atend_prof_ad : "co_atend_prof_ad"
    tb_ad_tipo_elegivel ||--o{ tb_atend_prof_ad : "co_ad_tipo_elegivel"
    tb_atend_prof_ad ||--o{ tb_atend_prof_ad_qst : "co_atend_prof_ad"
    tb_atend_prof ||--o{ tb_atend_prof_odonto : "co_atend_prof_odonto"
    tb_tipo_consulta_odonto ||--o{ tb_atend_prof_odonto : "tp_consulta_odonto"
    tb_tipo_edema ||--o{ tb_atend_prof_pre_natal : "tp_edema"
    tb_atend_prof ||--o{ tb_atend_prof_pre_natal : "co_atend_prof_pre_natal"
    tb_atend_prof ||--o{ tb_atend_prof_puericultura : "co_atend_prof_puericultura"
    tb_atend ||--o{ tb_atend_prof_tipo_encam_intrn : "co_atend"
    tb_tipo_encam_interno ||--o{ tb_atend_prof_tipo_encam_intrn : "tp_encam_interno"
    tb_agendado ||--o{ tb_atend_prof_tipo_encam_intrn : "co_agendado"
    tb_lotacao ||--o{ tb_atend_prof_tipo_encam_intrn : "co_lotacao"
    tb_prontuario ||--o{ tb_atestado : "co_prontuario"
    tb_atend_prof ||--o{ tb_atestado : "co_atend_prof"
    tb_prof ||--o{ tb_ativacao_agendamento_online : "co_prof"
    tb_prof ||--o{ tb_ator_papel : "co_prof"
    tb_prontuario ||--o{ tb_cds_atend_individual : "co_prontuario"
    tb_unidade_saude ||--o{ tb_cds_cad_individual : "co_unidade_saude"
    tb_lotacao ||--o{ tb_cfg_agenda_online_detalhe : "co_lotacao"
    tb_etnia ||--o{ tb_cidadao : "co_etnia"
    tb_estado_civil ||--o{ tb_cidadao : "co_estado_civil"
    tb_escolaridade ||--o{ tb_cidadao : "co_escolaridade"
    tb_tipo_logradouro ||--o{ tb_cidadao : "tp_logradouro"
    tb_raca_cor ||--o{ tb_cidadao : "co_raca_cor"
    tb_uf ||--o{ tb_cidadao : "co_uf"
    tb_localidade ||--o{ tb_cidadao : "co_localidade"
    tb_localidade ||--o{ tb_cidadao : "co_localidade_endereco"
    tb_cbo ||--o{ tb_cidadao : "co_cbo"
    tb_cds_tipo_cuidador ||--o{ tb_cidadao : "tp_cds_cuidador"
    tb_nacionalidade ||--o{ tb_cidadao : "co_nacionalidade"
    tb_pais ||--o{ tb_cidadao : "co_pais_nascimento"
    tb_pais ||--o{ tb_cidadao : "co_pais_exterior"
    tb_cidadao ||--o{ tb_cidadao_grupo : "co_cidadao_unificado"
    tb_cidadao ||--o{ tb_cidadao_grupo : "co_cidadao"
    tb_cidadao ||--o{ tb_cidadao_grupo : "co_cidadao_master"
    tb_cidadao ||--o{ tb_cidadao_nucleo_familiar : "co_cidadao"
    tb_cds_prof ||--o{ tb_cidadao_vinculacao_equipe : "co_prof_cadastrante_cds"
    tb_cidadao ||--o{ tb_cidadao_vinculacao_equipe : "co_cidadao"
    tb_lotacao ||--o{ tb_cidadao_vinculacao_equipe : "co_lotacao_cadastrante_pec"
    tb_cds_tipo_origem ||--o{ tb_cidadao_vinculacao_equipe : "tp_cds_origem"
    tb_lotacao ||--o{ tb_config_agenda_fechamento : "co_lotacao"
    tb_prontuario ||--o{ tb_encaminhamento : "co_prontuario"
    tb_atend_prof ||--o{ tb_encaminhamento : "co_atend_prof"
    tb_unidade_saude ||--o{ tb_equipe : "co_unidade_saude"
    tb_atend_prof ||--o{ tb_evolucao_avaliacao : "co_atend_prof"
    tb_atend_prof ||--o{ tb_evolucao_objetivo : "co_atend_prof"
    tb_prontuario ||--o{ tb_evolucao_odonto : "co_prontuario"
    tb_atend_prof_odonto ||--o{ tb_evolucao_odonto : "co_atend_prof_odonto"
    tb_atend_prof ||--o{ tb_evolucao_plano : "co_atend_prof"
    tb_atend_prof ||--o{ tb_evolucao_subjetivo : "co_atend_prof"
    tb_prontuario ||--o{ tb_exame_requisitado : "co_prontuario"
    tb_atend_prof ||--o{ tb_exame_requisitado : "co_atend_prof_resultado"
    tb_atend_prof ||--o{ tb_exame_requisitado : "co_atend_prof"
    tb_cidadao_grupo ||--o{ tb_historico_unificacao : "co_cidadao_grupo"
    tb_prof ||--o{ tb_historico_unificacao : "co_prof"
    tb_prof ||--o{ tb_importacao_cnes : "co_prof"
    tb_unidade_saude ||--o{ tb_imunobiologico_lote : "co_unidade_saude"
    tb_unidade_saude ||--o{ tb_integracao_horus : "co_unidade_saude_padrao"
    tb_unidade_saude ||--o{ tb_integracao_horus : "co_unidade_saude"
    tb_lotacao ||--o{ tb_justificativa_agenda : "co_lotacao_justificativa"
    tb_lotacao ||--o{ tb_justificativa_prontuario : "co_lotacao"
    tb_prontuario ||--o{ tb_justificativa_prontuario : "co_prontuario"
    tb_lotacao ||--o{ tb_justificativa_status_ciddao : "co_lotacao"
    tb_cidadao ||--o{ tb_justificativa_status_ciddao : "co_cidadao"
    tb_atend_prof ||--o{ tb_lembrete : "co_atend_prof"
    tb_prontuario ||--o{ tb_lembrete : "co_prontuario"
    tb_lotacao ||--o{ tb_lembrete_evolucao : "co_lotacao"
    tb_equipe ||--o{ tb_lotacao : "co_equipe"
    tb_unidade_saude ||--o{ tb_lotacao : "co_unidade_saude"
    tb_cbo ||--o{ tb_lotacao : "co_cbo"
    tb_prof ||--o{ tb_lotacao : "co_prof"
    tb_prontuario ||--o{ tb_medicamento_uso_continuo : "co_prontuario"
    tb_atend_prof ||--o{ tb_medicao : "co_atend_prof"
    tb_prontuario ||--o{ tb_neuro_alter_fenot : "co_prontuario"
    tb_atend_prof ||--o{ tb_neuro_alter_fenot_evolucao : "co_atend_prof"
    tb_prontuario ||--o{ tb_neuro_fator_risco : "co_prontuario"
    tb_atend_prof ||--o{ tb_neuro_fator_risco_evolucao : "co_atend_prof"
    tb_prontuario ||--o{ tb_neuro_marco : "co_prontuario"
    tb_atend_prof ||--o{ tb_neuro_marco_evolucao : "co_atend_prof"
    tb_prontuario ||--o{ tb_odontograma : "co_prontuario"
    tb_atend_prof_odonto ||--o{ tb_odontograma : "co_atend_prof_odonto"
    tb_prontuario ||--o{ tb_orientacao : "co_prontuario"
    tb_atend_prof ||--o{ tb_orientacao : "co_atend_prof"
    tb_cidadao ||--o{ tb_pessoa_fisica_imagem : "co_cidadao"
    tb_prontuario ||--o{ tb_pre_natal : "co_prontuario"
    tb_prontuario ||--o{ tb_problema : "co_prontuario"
    tb_atend_prof ||--o{ tb_problema_evolucao : "co_atend_prof"
    tb_lotacao ||--o{ tb_proced_solicitado : "co_lotacao_solicitante"
    tb_prontuario ||--o{ tb_proced_solicitado : "co_prontuario"
    tb_lotacao ||--o{ tb_proced_solicitado : "co_lotacao_executante"
    tb_tipo_logradouro ||--o{ tb_prof : "tp_logradouro"
    tb_uf ||--o{ tb_prof : "co_uf_emissora_conselho_classe"
    tb_usuario ||--o{ tb_prof : "co_usuario"
    tb_localidade ||--o{ tb_prof : "co_localidade_endereco"
    tb_uf ||--o{ tb_prof : "co_uf"
    tb_conselho_classe ||--o{ tb_prof : "co_conselho_classe"
    tb_cidadao ||--o{ tb_prontuario : "co_cidadao"
    tb_prontuario ||--o{ tb_prontuario_grupo_historico : "co_prontuario"
    tb_prontuario ||--o{ tb_prontuario_grupo_historico : "co_prontuario_grupo"
    tb_unidade_saude ||--o{ tb_prontuario_unidade_saude : "co_unidade_saude"
    tb_atend_prof ||--o{ tb_qst_questionario_respondido : "co_atend_prof"
    tb_atend_prof ||--o{ tb_receita_medicamento : "co_atend_prof"
    tb_atend_prof ||--o{ tb_requisicao_exame : "co_atend_prof"
    tb_atend_prof ||--o{ tb_res_envio : "co_atend_prof"
    tb_prontuario ||--o{ tb_sinan_notificacao_evolucao : "co_prontuario"
    tb_atend_prof ||--o{ tb_sinan_notificacao_evolucao : "co_atend_prof"
    tb_tipo_unidade_saude ||--o{ tb_unidade_saude : "tp_unidade_saude"
    tb_uf ||--o{ tb_unidade_saude : "co_uf"
    tb_localidade ||--o{ tb_unidade_saude : "co_localidade_endereco"
    tb_tipo_logradouro ||--o{ tb_unidade_saude : "tp_logradouro"
    tb_atend_prof ||--o{ tb_vacinacao : "co_atend_prof"
    tb_prontuario ||--o{ tb_vacinacao : "co_prontuario"

%% Gerado com sucesso.
%% Tabelas envolvidas: 121
%% Relacionamentos: 169
