services:
  database:
    container_name: esus_database
    image: esus_database:1.0.0
    build: database
    ports:
      - '5432:5432'
    networks:
      - esus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esus"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  webserver:
    container_name: esus_webserver
    image: esus_webserver:5.2.31
    build:
      context: webserver
      args:
        - URL_DOWNLOAD_ESUS=https://arquivos.esusaps.ufsc.br/PEC/bacaf0eccedf69d4/5.4.26/eSUS-AB-PEC-5.4.26-Linux64.jar
    environment:
      - APP_DB_URL=jdbc:postgresql://database:5432/esus
      - APP_DB_USER=esus
      - APP_DB_PASSWORD=esus
    ports:
      - '8080:8080'
    networks:
      - esus_network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  pgadmin:
    container_name: esus_pgadmin
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@esus.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - "5050:80"
    networks:
      - esus_network
    depends_on:
      - database

networks:
  esus_network:
    driver: bridge
